services:
  # Service PHP-FPM pour Symfony (PHP)
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_symfony
    volumes:
      - ./:/var/www/html
      - ./docker/supervisor:/etc/supervisor/conf.d:ro
      - cron_logs:/var/log
    environment:
      - APP_ENV=dev
    networks:
      - symfony-network
    depends_on:
      - database

  # Service MySQL pour la base de données
  database:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf7-ecommerce
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      timeout: 5s
      retries: 10
      interval: 5s
    restart: always

  # Service Nginx pour le serveur web
  webserver:
    image: nginx:alpine
    container_name: nginx_symfony
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      - symfony-network

  # Service PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - database
    networks:
      - symfony-network

  # Service Mercure
  mercure:
    image: dunglas/mercure
    container_name: mercure
    restart: unless-stopped
    environment:
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://127.0.0.1:8000
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    networks:
      - symfony-network

volumes:
  cron_logs:
  db_data:
  mercure_data:
  mercure_config:

networks:
  symfony-network:
    driver: bridge
